services:
  nginx:
    container_name: nginx #Nom des containers. (correspond a run --name)
    build: ./requirements/nginx/ #Permet de build l'image si elle n'existe pas.
    image: nginx:42 #Nom de l'image a run ou rename l'image constuite par build.
    ports: #(-p 443:443)
      - 443:443
    #depends_on: Permet de controler l'ordre du lancement des containers.
      #- "wordpress"
    restart: on-failure
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    env_file : .env
    restart: on-failure
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    env_file: .env
    restart: on-failure
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge
