services:
  nginx:
    container_name: nginx #Nom des containers. (correspond a run --name)
    build: ./requirements/nginx/ #Permet de build l'image si elle n'existe pas.
    image: nginx:42 #Nom de l'image a run ou rename l'image constuite par build.
    ports: #(-p 443:443)
      - 443:443
    #depends_on: Permet de controler l'ordre du lancement des containers.
      #- "wordpress"
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mariadb:42
    env_file : .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    env_file: .env
    restart: on-failure
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_PATH}/wordpress-data'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATA_PATH}/mariadb-data'
